apiVersion: v1
kind: Secret
metadata:
  name: cloudopshub-secrets
  namespace: {{ .Values.namespace }}
type: Opaque

stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}

  RABBITMQ_USER: {{ .Values.rabbitmq.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | quote }}