services:

  postgres:
    image: postgres:17
    container_name: cloudopshub-postgres
    environment:
      POSTGRES_DB: cloudopshub
      POSTGRES_USER: cloudops
      POSTGRES_PASSWORD: cloudops_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudops -d cloudopshub"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4-management
    container_name: cloudopshub-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: cloudops
      RABBITMQ_DEFAULT_PASS: cloudops_dev_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  order-service:
    image: cloudopshub/order-service:local
    container_name: cloudopshub-order-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=cloudopshub;Username=cloudops;Password=cloudops_dev_password

      RabbitMq__Host: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: cloudops
      RabbitMq__Password: cloudops_dev_password

      Outbox__PollingIntervalSeconds: 5
      Outbox__MaxAttempts: 10
      Outbox__BatchSize: 20

    ports:
      - "5163:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-service:
    image: cloudopshub/notification-service:local
    container_name: cloudopshub-notification-service
    environment:
      RabbitMq__Host: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: cloudops
      RabbitMq__Password: cloudops_dev_password

    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data: